language: java
jdk:
- oraclejdk7
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
before_install:
- openssl aes-256-cbc -K $encrypted_4b7767003602_key -iv $encrypted_4b7767003602_iv
  -in gradle.properties.enc -out gradle.properties -d
