language: java
sudo: false
jdk:
- oraclejdk7
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/dists/gradle-2.7-bin/"
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_4b7767003602_key -iv $encrypted_4b7767003602_iv
  -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- ./gradlew jacocoTestReport coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bb06ddbc2f1ed0c5ad2e
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false
